[package]
name = "merkletree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
risc0-zkvm = { version = "0.19.1", default-features = false }
serde = "1.0"
merkle_light = "0.4.0"